DELETE FROM `player`;
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('1', 'Pht', '1', '-4.5');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('3', 'Morösch', '1', '-153.5');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('4', 'Aimsi', '1', '112.0');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('5', 'Julezzz', '1', '60.0');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('6', 'Schmopfel', '1', '27.0');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('7', 'Vicly', '1', '-25.5');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('8', 'Lyonwas', '1', '25.5');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('10', 'Julia', '1', '-34.0');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('11', 'Joni', '0', '-4.5');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('12', 'Aleks', '1', '26.5');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('13', 'Annabelle', '1', '6.0');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('14', 'Gästli', '0', '-39.5');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('15', 'Testli', '0', '0.0');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('16', 'Benny', '1', '0.0');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('17', 'Wibke', '0', '0.0');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('18', 'WiK', '0', '0.0');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('19', '0xMoritz', '0', '0.0');
INSERT INTO `player` (`id`, `name`, `active`, `start_points`) VALUES ('20', 'Joni :)', '0', '0.0');
