DELETE FROM `special_card`;
INSERT INTO `special_card` (`id`, `name`) VALUES ('1', 'Gegengenscherdamen');
INSERT INTO `special_card` (`id`, `name`) VALUES ('2', 'Gescherdamen');
INSERT INTO `special_card` (`id`, `name`) VALUES ('3', 'Heidfrau');
INSERT INTO `special_card` (`id`, `name`) VALUES ('4', 'Heidmann');
INSERT INTO `special_card` (`id`, `name`) VALUES ('5', 'Hyperschweinchen');
INSERT INTO `special_card` (`id`, `name`) VALUES ('6', 'Kemmerich');
INSERT INTO `special_card` (`id`, `name`) VALUES ('7', 'Linksdrehender Gehängter');
INSERT INTO `special_card` (`id`, `name`) VALUES ('8', 'Schweinchen');
INSERT INTO `special_card` (`id`, `name`) VALUES ('9', 'Superschweinchen');
